python 002_Create_Deepest_model_GOWALLA.py
python 002_Create_RandomForest_GOWALLA.py
python 002_Create_TULER_model_GOWALLA.py
python 002_Create_TULVAE_model_GOWALLA.py
python 002_Create_XGBoost_model_GOWALLA.py
